[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && ./mvnw spring-boot:run"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "hr-manual-backend"
source = "backend"

[services.variables]
PORT = "8080"
JAVA_OPTS = "-Xmx512m" 