[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && ./mvnw spring-boot:run"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "hr-manual-backend"
source = "backend"

[services.variables]
PORT = "8080"
JAVA_OPTS = "-Xmx512m"
NODE_ENV = "production"

[[services]]
name = "hr-manual-frontend"
source = "frontend"

[services.variables]
NODE_ENV = "production"
REACT_APP_API_BASE_URL = "${{hr-manual-backend.RAILWAY_STATIC_URL}}"
REACT_APP_APP_NAME = "HR Manual App"
REACT_APP_VERSION = "1.0.0"

# Build configuration
[build.frontend]
buildCommand = "npm install && npm run build"
publishDirectory = "build"

[build.backend]
buildCommand = "./mvnw clean package -DskipTests"
