services:
  - type: web
    name: hr-manual-backend
    env: java
    buildCommand: cd backend && ./mvnw clean package -DskipTests
    startCommand: cd backend && java -jar target/hr-manual-app-1.0.0.jar
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: FIREBASE_CONFIG_PATH
        value: classpath:firebase-config.json
      - key: ALLOWED_ORIGINS
        value: https://hr-manual-frontend.onrender.com

  - type: web
    name: hr-manual-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    plan: free
    envVars:
      - key: REACT_APP_API_BASE_URL
        fromService:
          type: web
          name: hr-manual-backend
          property: host
      - key: REACT_APP_APP_NAME
        value: HR Manual App
      - key: REACT_APP_VERSION
        value: 1.0.0

databases:
  - name: hr-manual-db
    databaseName: hrmanual
    user: hruser
    plan: free

envVarGroups:
  - name: shared-config
    envVars:
      - key: NODE_ENV
        value: production
      - key: JAVA_OPTS
        value: -Xmx512m
